### ISSUE TITLE
recurrent events for defined week of month on sunday are scheduled on monday 

### ISSUE THREAD

**Issue by jankowa** [rapilodev/racalmas#1]
to reproduce: in a series schedule events as following:

start: on any sunday at any time.
recurrence: week of month
end: any date in the future
week of month: 1
weekday: sunday
every nth time: any

the result: the events are not scheduled on sunday but on monday.

**Comment by rapilodev** [comment]
Hi jankowa, 
Thanks for submitting, I will try to reproduce this. 
What country/timezone is your browser running at?
Thanks, Milan

**Comment by rapilodev** [comment]
has been fixed by 777a49c.
Thanks for your support, Milan
